name: example
description: Example app demonstrating flutter_map_gesture_drawing package
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map_gesture_drawing:
    path: ../  # This points to the package
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

